export default [
  {
    id: 193,
    title: '1.17',
    type: {
      id: 1,
      name: 'Safety and Efficacy',
    },
    description:
      'Happiness can be found even in the darkest of times if only one remembers to turn on the light.',
    role: 'Data Set Owner',
    leadList: [
      {
        id: 'ADQANQA4ADcANQAy',
        firstname: 'Tester',
        lastname: 'Testers',
      },
      {
        id: 'ADMAMAAxADQANgA1ADY=',
        firstname: 'Jhon',
        lastname: 'Doe',
      },
    ],
    created: 1608881325102,
    status: {
      id: 3,
      name: 'Completed',
      availableActions: ['CREATE_PAPER', 'PUBLISH_PAPER'],
    },
    updated: 1621345127417,
    startDate: 1608794925000,
    endDate: 1609054125000,
    favorite: null,
    permissions: {},
    privacy: false,
  },
  {
    id: 407,
    title: '1.17 part 2',
    type: {
      id: 5,
      name: 'Sales and Marketing',
    },
    description:
      'It is the unknown we fear when we look upon death and darkness, nothing more.\n\n\n\n\n\n\n\n\n\n\n\n\nrewtw',
    role: 'Data Set Owner',
    leadList: [
      {
        id: 'ADQANQA4ADcANQAy',
        firstname: 'Tester',
        lastname: 'Testers',
      },
    ],
    created: 1610416547368,
    status: {
      id: 4,
      name: 'Archived',
      availableActions: ['CREATE_PAPER'],
    },
    updated: 1621347835152,
    startDate: 1610416547368,
    endDate: 1610589349000,
    favorite: null,
    permissions: {},
    privacy: false,
  },
  {
    id: 642,
    title: '1.17.1',
    type: {
      id: 2,
      name: 'Clinical Trial Design',
    },
    description: 'regress testing',
    role: 'Data Set Owner',
    leadList: [
      {
        id: 'ADQAMgA1ADkAOAA0ADA=',
        firstname: 'Jane',
        lastname: 'Doe',
      },
    ],
    created: 1617286239390,
    status: {
      id: 2,
      name: 'Active',
      availableActions: ['CREATE_PAPER'],
    },
    updated: 1619786381953,
    startDate: 1617286239390,
    endDate: null,
    favorite: null,
    permissions: {},
    privacy: false,
  },
  {
    id: 43,
    title: 'ac-CORORT',
    type: {
      id: 6,
      name: 'Other',
    },
    description: null,
    role: 'Data Set Owner',
    leadList: [
      {
        id: 'ADYANQA1ADMANgAw',
        firstname: 'acma',
        lastname: '2019',
      },
      {
        id: 'ADIAOQA0ADkAMQAyADA=',
        firstname: 'some',
        lastname: 'user',
      },
    ],
    created: 1608654148437,
    status: {
      id: 2,
      name: 'Active',
      availableActions: ['CREATE_PAPER'],
    },
    updated: 1621420479489,
    startDate: 1608654148437,
    endDate: null,
    favorite: null,
    permissions: {},
    privacy: false,
  },
  {
    id: 44,
    title: 'ac-PLEPLP',
    type: {
      id: 2,
      name: 'Clinical Trial Design',
    },
    description: null,
    role: 'Data Set Owner',
    leadList: [
      {
        id: 'ADYANQA1ADMANgAw',
        firstname: 'acma',
        lastname: '2019',
      },
      {
        id: 'ADIAOQA0ADkAMQAyADA=',
        firstname: 'some',
        lastname: 'user',
      },
    ],
    created: 1608735591342,
    status: {
      id: 2,
      name: 'Active',
      availableActions: ['CREATE_PAPER'],
    },
    updated: 1611760769740,
    startDate: 1608735591342,
    endDate: null,
    favorite: null,
    permissions: {},
    privacy: false,
  },
  {
    id: 677,
    title: 'bug_test',
    type: {
      id: 2,
      name: 'Clinical Trial Design',
    },
    description: null,
    role: 'Data Set Owner, Lead Investigator',
    leadList: [
      {
        id: 'ADMAMgA3ADYAOAAw',
        firstname: 'Autoadmin',
        lastname: 'Autoadmin',
      },
    ],
    created: 1621236321235,
    status: {
      id: 2,
      name: 'Active',
      availableActions: ['CREATE_PAPER'],
    },
    updated: 1621236372782,
    startDate: 1621236321235,
    endDate: null,
    favorite: null,
    permissions: {},
    privacy: true,
  },
  {
    id: 277,
    title: 'Dimension C-132365',
    type: {
      id: 3,
      name: 'Clinical Trial Patient Enrollment',
    },
    description:
      'To the well-organized mind, death is but the next great adventure.',
    role: null,
    leadList: [
      {
        id: 'ADQANQA4ADcANQAy',
        firstname: 'Tester',
        lastname: 'Testers',
      },
    ],
    created: 1609168175873,
    status: {
      id: 1,
      name: 'Initiate',
      availableActions: [],
    },
    updated: 1609168185162,
    startDate: 1609168175873,
    endDate: 1609340985000,
    favorite: null,
    permissions: {},
    privacy: false,
  },
  {
    id: 674,
    title: 'Earth2',
    type: {
      id: 1,
      name: 'Safety and Efficacy',
    },
    description: 'It does not do to dwell on dreams and forget to live.',
    role: null,
    leadList: [
      {
        id: 'ADQANQA4ADcANQAy',
        firstname: 'Tester',
        lastname: 'Testers',
      },
    ],
    created: 1617956432420,
    status: {
      id: 1,
      name: 'Initiate',
      availableActions: [],
    },
    updated: 1617956444852,
    startDate: 1617956432420,
    endDate: 1618129244000,
    favorite: null,
    permissions: {},
    privacy: false,
  },
  {
    id: 680,
    title: 'My New Study',
    type: {
      id: 2,
      name: 'Clinical Trial Design',
    },
    description: null,
    role: 'Data Set Owner',
    leadList: [
      {
        id: 'ADMAMAAxADQANgA1ADY=',
        firstname: 'Jhon',
        lastname: 'Doe',
      },
    ],
    created: 1621430925232,
    status: {
      id: 2,
      name: 'Active',
      availableActions: ['CREATE_PAPER'],
    },
    updated: 1621436062903,
    startDate: 1621430925232,
    endDate: null,
    favorite: null,
    permissions: {},
    privacy: true,
  },
  {
    id: 679,
    title: 'My study',
    type: {
      id: 2,
      name: 'Clinical Trial Design',
    },
    description: null,
    role: 'Data Set Owner, Lead Investigator',
    leadList: [
      {
        id: 'ADMAMgA3ADYAOAAw',
        firstname: 'Autoadmin',
        lastname: 'Autoadmin',
      },
    ],
    created: 1621345724559,
    status: {
      id: 2,
      name: 'Active',
      availableActions: ['CREATE_PAPER'],
    },
    updated: 1621415543789,
    startDate: 1621345724559,
    endDate: null,
    favorite: null,
    permissions: {},
    privacy: true,
  },
  {
    id: 496,
    title: 'Screaming Sun Earth272',
    type: {
      id: 3,
      name: 'Clinical Trial Patient Enrollment',
    },
    description:
      'Of course it is happening inside your head, Harry, but why on earth should that mean that it is not real?',
    role: 'Data Set Owner',
    leadList: [
      {
        id: 'ADQANQA4ADcANQAy',
        firstname: 'Tester',
        lastname: 'Testers',
      },
    ],
    created: 1610502930059,
    status: {
      id: 2,
      name: 'Active',
      availableActions: ['CREATE_PAPER'],
    },
    updated: 1610507017099,
    startDate: 1610502930059,
    endDate: 1610675730000,
    favorite: null,
    permissions: {},
    privacy: false,
  },
  {
    id: 1,
    title: 'Study #1',
    type: {
      id: 6,
      name: 'Other',
    },
    description: 'descr',
    role: null,
    leadList: [
      {
        id: 'ADIANgAyADEANAA0',
        firstname: 'admin',
        lastname: 'admin',
      },
    ],
    created: 1506470400000,
    status: {
      id: 2,
      name: 'Active',
      availableActions: ['CREATE_PAPER'],
    },
    updated: 1506470400000,
    startDate: 1506470400000,
    endDate: 1506470400000,
    favorite: null,
    permissions: {},
    privacy: false,
  },
];
