export enum UseFileExplorerStatus {
  LOADING_FILE = 'LOADING_FILE',
  LOADED_FILE_DONE = 'LOADED_FILE_DONE',
  LOADED_FILE_FAILED = 'LOADED_FILE_FAILED',
}

export enum UseFileExplorer {
  SAVE_FILE_REQUEST = 'SAVE_FILE_REQUEST',
  SAVE_FILES_REQUEST_DONE = 'SAVE_FILES_REQUEST_DONE',
  SAVE_FILES_REQUEST_FAILED = 'SAVE_FILES_REQUEST_FAILED',
  SELECT_FILE = 'SELECT_FILE',
  LOAD_FILE_REQUEST = 'LOAD_FILE_REQUEST',
  LOAD_FILE_REQUEST_DONE = 'LOAD_FILE_REQUEST_DONE',
  LOAD_FILE_REQUEST_FAILED = 'LOAD_FILE_REQUEST_FAILED',
}

export enum FileExplorerTypes {
  FOLDER = 'FOLDER',
  FILE = 'FILE',
  ZIP = 'ZIP',
  COMPONENT = 'COMPONENT',
}
