export enum AuthModeActions {
  FETCH_AUTH_MODE = "FETCH_AUTH_MODE",
  FETCH_AUTH_MODE_DONE = "FETCH_AUTH_MODE_DONE",
  FETCH_AUTH_MODE_FAILED = "FETCH_AUTH_MODE_FAILED",

  FETCH_SETUP_STATUS = "FETCH_SETUP_STATUS",
  FETCH_SETUP_STATUS_DONE = "FETCH_SETUP_STATUS_DONE",
  FETCH_SETUP_STATUS_FAILED = "FETCH_SETUP_STATUS_FAILED",

  PERFORM_SETUP = "PERFORM_SETUP",
  PERFORM_SETUP_DONE = "PERFORM_SETUP_DONE",
  PERFORM_SETUP_FAILED = "PERFORM_SETUP_FAILED",

  PERFORM_REGISTER = "PERFORM_REGISTER",
  PERFORM_REGISTER_DONE = "PERFORM_REGISTER_DONE",
  PERFORM_REGISTER_FAILED = "PERFORM_REGISTER_FAILED",
}
