export enum EntityActions {
  GET_ENTITY = 'GET_ENTITY',
  GET_ENTITY_SUCCESS = 'GET_ENTITY_SUCCESS',
  GET_ENTITY_ERROR = 'GET_ENTITY_ERROR',

  DELETE_ENTITY = 'DELETE_ENTITY',
  DELETE_ENTITY_SUCCESS = 'DELETE_ENTITY_SUCCESS',
  DELETE_ENTITY_ERROR = 'DELETE_ENTITY_ERROR',

  UPDATE_ENTITY = 'UPDATE_ENTITY',
  UPDATE_ENTITY_SUCCESS = 'UPDATE_ENTITY_SUCCESS',
  UPDATE_ENTITY_ERROR = 'UPDATE_ENTITY_ERROR',

  SET_VERSION = 'SET_VERSION',
  REVERT_VERSION = 'REVERT_VERSION',

  COPY_ENTITY = 'COPY_ENTITY',
  COPY_ENTITY_SUCCESS = 'COPY_ENTITY_SICCESS',
  COPY_ENTITY_ERROR = 'COPY_ENTITY_ERROR',
}