export * from './BaseResponseInterface';
export * from './DataSourceDTOInterface';
export * from './DBMSTypesInterface';
export * from './DescriptorInterface';
export * from './UserDTOInterface';
export * from './UserDTOSearchInterface';
export * from './PageableDTOInterface';
export * from './SubmissionDTOInterface';
export * from './AuthorDTOInterface';