export enum UserActions {
  USER_SIGN_IN_REQUEST = 'USER_SIGN_IN_REQUEST',
  USER_SIGN_IN_REQUEST_DONE = 'USER_SIGN_IN_REQUEST_DONE',
  USER_SIGN_IN_REQUEST_FAILED = 'USER_SIGN_IN_REQUEST_FAILED',

  USER_SIGN_OUT_REQUEST = 'USER_SIGN_OUT_REQUEST',
  USER_SIGN_OUT_REQUEST_DONE = 'USER_SIGN_OUT_REQUEST_DONE',
  USER_SIGN_OUT_REQUEST_FAILED = 'USER_SIGN_OUT_REQUEST_FAILED',

  USER_GET_REQUEST = 'USER_GET_REQUEST',
  USER_GET_REQUEST_DONE = 'USER_GET_REQUEST_DONE',
  USER_GET_REQUEST_FAILED = 'USER_GET_REQUEST_FAILED',

  RESET_USER_DATA = 'RESET_USER_DATA',

  SWITCH_TENANT = 'SWITCH_TENANT',
}
