// VERSION 3
// export enum AnalysisSubmissionStatus {
//   PENDING = 'PENDING',
//   NOT_APPROVED = 'NOT_APPROVED',
//   STARTING = 'STARTING',
//   QUEUE_PROCESSING = 'QUEUE_PROCESSING',
//   IN_PROGRESS = 'IN_PROGRESS',
//   EXECUTED = 'EXECUTED',
//   FAILED = 'FAILED',
//   APPROVED = 'APPROVED',
//   EXECUTED_REJECTED = 'EXECUTED_REJECTED',
//   FAILED_REJECTED = 'FAILED_REJECTED',
//   EXECUTED_PUBLISHED = 'EXECUTED_PUBLISHED',
//   FAILED_PUBLISHED = 'FAILED_PUBLISHED',
//   INITIAL = 'INITIAL',
//   AWAITING_APPROVAL = 'AWAITING_APPROVAL',
//   AWAITING_PUBLISHING_APPROVAL = 'AWAITING_PUBLISHING_APPROVAL',
//   PUBLISHED = 'PUBLISHED',
//   DISMISSED = 'DISMISSED',
// }

export enum AnalysisSubmissionStatus {
  INITIAL = 'INITIAL',
  AWAITING_APPROVAL = 'AWAITING_APPROVAL',
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  AWAITING_PUBLISHING_APPROVAL = 'AWAITING_PUBLISHING_APPROVAL',
  PUBLISHED = 'PUBLISHED',
  FAILED = 'FAILED',
  DISMISSED = 'DISMISSED',
}
