// VERSION #3
export enum AnalysisTypes {
  COHORT = 'COHORT',
  COHORT_HERACLES = 'COHORT_HERACLES',
  COHORT_CHARACTERIZATION = 'COHORT_CHARACTERIZATION',
  COHORT_PATHWAY = 'PATHWAY',
  ESTIMATION = 'ESTIMATION',
  PREDICTION = 'PREDICTION',
  INCIDENCE = 'INCIDENCE_RATE',
  CUSTOM = 'CUSTOM',
  REPORTING = 'REPORTING',
  STRATEGUS = 'STRATEGUS',
  SIMPLE_COUNTS_CHARACTERIZATION = 'SIMPLE_COUNTS_CHARACTERIZATION',
}
