export enum AnalysisType {
  COHORT = 'COHORT',
  COHORT_HERACLES = 'COHORT_HERACLES',
  COHORT_CHARACTERIZATION = 'COHORT_CHARACTERIZATION',
  COHORT_PATHWAY = 'COHORT_PATHWAY',
  ESTIMATION = 'ESTIMATION',
  PREDICTION = 'PREDICTION',
  INCIDENCE = 'INCIDENCE',
  CUSTOM = 'CUSTOM',
  REPORTING = 'REPORTING',
}
