// VERSION #3
export enum CriteriaTypes {
  CONDITION_ERA = 'ConditionEra',
  CONDITION_OCCURRENCE = 'ConditionOccurrence',
  DEATH = 'Death',
  DEVICE_EXPOSURE = 'DeviceExposure',
  DOSE_ERA = 'DoseEra',
  DRUG_ERA = 'DrugEra',
  DRUG_EXPOSURE = 'DrugExposure',
  MEASUREMENT = 'Measurement',
  OBSERVATION = 'Observation',
  OBSERVATION_PERIOD = 'ObservationPeriod',
  PAYER_PLAN_PERIOD = 'PayerPlanPeriod',
  PROCEDURE_OCCURRENCE = 'ProcedureOccurrence',
  SPECIMEN = 'Specimen',
  VISIT = 'VisitOccurrence',
  VISIT_DETAILS = 'VisitDetails',
  DEMOGRAPHIC = 'Demographic',
  GROUP = 'Group',
  LOCATION_REGION = 'LocationRegion',
}
