export enum DataSourceReportVariant {
  DASHBOARD = 'dashboard',
  DATA_DENSITY = 'datadensity',
  PERSON = 'person',
  VISITS = 'visits',
  CONDITIONS = 'conditions',
  CONDITION_ERAS = 'conditionera',
  PROCEDURES = 'procedures',
  DRUG_EXPOSURES = 'drugexposures',
  DRUG_ERAS = 'drugeras',
  MEASUREMENT = 'measurement',
  OBSERVATIONS = 'observations',
  OBSERVATION_PERIODS = 'observationperiods',
  DEATH = 'death',
  ACHILLES_HEEL = 'achillesheel',
}
