export enum DBMSType {
  POSTGRESQL = 'POSTGRESQL',
  MS_SQL_SERVER = 'MS_SQL_SERVER',
  PDW = 'PDW',
  BIGQUERY = 'BIGQUERY',
  NETEZZA = 'NETEZZA',
  ORACLE = 'ORACLE',
  IMPALA = 'IMPALA',
  REDSHIFT = 'REDSHIFT',
  HIVE = 'HIVE',
  SPARK = 'SPARK',
  SNOWFLAKE = 'SNOWFLAKE',
  SYNAPSE = 'SYNAPSE'
}

