export enum EntityTypes {
  COHORT = 'COHORT',
  CONCEPT_SET = 'CONCEPT_SET',
  FEATURE_ANALYSIS = 'FEATURE_ANALYSIS',
  DATA_SOURCE = 'DATA_SOURCE',
  METADATA = 'METADATA',
  USERS = 'USERS',
  ANALYSIS = 'ANALYSIS',
}
