// VERSION #3
export enum IntervalInclude {
  STARTING_WITH = 'STARTING_WITH',
  CONTAINING = 'CONTAINING',
  ENDING_WITH = 'ENDING_WITH',
  NOT_STARTING_WITH = 'NOT_STARTING_WITH',
  NOT_CONTAINING = 'NOT_CONTAINING',
  NOT_ENDING_WITH = 'NOT_ENDING_WITH',
}
