export enum ProfessionalType {
  IT_PROFESSIONAL = 'IT_PROFESSIONAL',
  MEDICAL = 'MEDICAL',
  EPIDEMIOLOGY = 'EPIDEMIOLOGY',
  DRUG_SAFETY = 'DRUG_SAFETY',
  SALES_MARKETING = 'SALES_MARKETING',
  FINANCE = 'FINANCE',
  ACADEMIC_RESEARCH = 'ACADEMIC_RESEARCH',
}
