export enum SubmissionStatus {
  CREATED = 'CREATED',
  EXECUTED = 'EXECUTED',
  EXECUTING = 'EXECUTING',
  EXECUTION_FAILURE = 'EXECUTION_FAILURE',
  ABORTING = 'ABORTING',
  ABORT_FAILURE = 'ABORT_FAILURE',
  ABORTED = 'ABORTED',
  DEAD = 'DEAD'
}