export enum SubmissionStatus {
  CREATED = 'CREATED',
  EXECUTED = 'EXECUTED',
  PENDING = 'PENDING',
  EXECUTING = 'EXECUTING',
  EXECUTION_FAILURE = 'EXECUTION_FAILURE',
  FAILED = 'FAILED',
  SENDING_TO_CENTRAL_FAILURE = 'SENDING_TO_CENTRAL_FAILURE',
  FILES_DOWNLOAD_FAILURE = 'FILES_DOWNLOAD_FAILURE',
  EXECUTION_READY = 'EXECUTION_READY',
  CLOSED = 'CLOSED',
  DEAD = 'DEAD'
} 