export enum UseSystemSettings {
  GET_LIST = 'GET_LIST',
  GET_LIST_DONE = 'GET_LIST_DONE',
  GET_LIST_FAILED = 'GET_LIST_FAILED',
  UPDATED_VALUE = 'UPDATED_VALUE',
  UPDATED_VALUE_DONE = 'UPDATED_VALUE_DONE',
  UPDATED_VALUE_FAILED = 'UPDATED_VALUE_FAILED'
}